### ISSUE TITLE
Request for exposing port 6162

### ISSUE THREAD

**Issue by Kris0x0000** [kjake/docker-veeam-backup-repository#2]
Hi,

Could you expose tcp/6162 port on the container? This is the default port used by the Veeam Data Mover. Without it I couldn't get it to work so I've builded my image based on your's. It would be nice to have it "out of the box".

```
FROM kjake/veeam-backup-repository:latest
EXPOSE 22 6162
```

**Comment by kjake** [comment]
@KrisTheGreat - Check out my updates to the README if you need further assistance on getting Data Mover working
